# Gestion des inscriptions - Configuration de l'application

springdoc.swagger-ui.path=/swagger-ui.html

spring.application.name=gestion_inscription
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_inscription
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# mail config

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=m7hels@gmail.com
spring.mail.password=rssn mtuw blbk qara
spring.mail.properties.mail.mine.charset=UTF
spring.mail.properties.mail.smtp.writetimeout=10000
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.verify.host=http://localhost:8085
spring.mail.from=noreply@your-domain.com

#sms twilio config

TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=

# WebSocket Configuration
# spring.websocket.allowed-origins=*

server.port=8085

# Planification des rappels
app.notification.reminder-time=09:00

# Logging SQL
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace

# Configuration JWT
gestin_inscription.app.jwtSecret=F06PBJ6GzaTRCyiAycvwVHn0Mkgi9ztGpl6DIkULwtDcJ2y17uDwYS0XdrNjIIfWKAvWPoyAwBLHvHKnDzzPmmXWEpaRbWVG8zGkIViUWumw64U6nGOE2d5a7Zb9sQaOrmYfxCHTbPinjbSOoMuSJhk793ewS3COygGtNoAKjGZgiwzlWpIgAYDxTDHzJAL6gp8YEuxmq5CpovVtTm6V4hvEf3kA7zBmjWctjTULcXlQ2VjfhH6WI48lJ5gqBZWl
gestin_inscription.app.jwtExpirationMs=86400000

#Admin credentials
app.admin.username=super-admin
app.admin.password=adminpass
app.admin.email=admin@example.com